Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2023-10, with the labels that each got.

#111 Update params.env
  config/base/params.env
Labels: ok-to-test, lgtm

#109 Custom image support for local CI
  tests/scripts/install.sh
Labels: kind/enhancement, lgtm

#115 Update CI for new operator image spec
  tests/scripts/install.sh
Labels: ok-to-test

#116 Release 1.10.2
  config/base/params.env
Labels: ok-to-test, lgtm

#118 feat: Add reconcile delay
  config/rbac/role.yaml
  controllers/constants.go
  controllers/inference_services.go
  controllers/suite_test.go
  controllers/trustyaiservice_controller.go
  main.go
  tests/crds/monitoring.coreos.com_servicemonitors.yaml
  tests/crds/route_crd.yaml
  tests/crds/serving.kserve.io_servingruntimes.yaml
Labels: kind/bug, ok-to-test, lgtm

#120 fix: Match go version with ODHv2
  go.mod
Labels: kind/enhancement, ok-to-test, lgtm

#119 fix: Refactor status updates
  README.md
  api/v1alpha1/trustyaiservice_types.go
  controllers/conditions.go
  controllers/constants.go
  controllers/inference_services.go
  controllers/statuses.go
  controllers/suite_test.go
  controllers/trustyaiservice_controller.go
Labels: kind/bug, ok-to-test

#125 feat: Add Route status
  controllers/constants.go
  controllers/statuses.go
  controllers/trustyaiservice_controller.go
Labels: kind/enhancement, lgtm

#124 fix: Update Go dependencies
  go.mod
  go.sum
Labels: kind/bug, ok-to-test, priority/high

#128 Release 1.10.3
  config/base/params.env
Labels: ok-to-test, lgtm, release

#129 Release 1.11.0
  config/base/params.env
Labels: ok-to-test, lgtm, release

#131 Upgrade google.golang.org/grpc
  go.mod
  go.sum
Labels: kind/bug, kind/enhancement, ok-to-test, lgtm, priority/high

#133 Remove proxy external image
  config/base/manager_auth_proxy_patch.yaml
Labels: kind/enhancement, ok-to-test, lgtm, rhods-2.4
