Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2023-07, with the labels that each got.

#70 Stop retrying if ModelMesh finalizer returns an error
  controllers/finalizers.go
Labels: kind/bug

#72 Correct finalizer name
  controllers/trustyaiservice_controller.go
Labels: kind/bug

#78 Add custom TrustyAI service image
  config/manager/kustomization.yaml
Labels: kind/enhancement

#79 Remove operator's unused namespace
  config/base/kustomization.yaml
  config/manager/manager.yaml
Labels: kind/bug

#85 GH Build+Release Actions
  .github/workflows/build-and-push.yaml
  Dockerfile
Labels: kind/enhancement

#91 Refactor reconcile return values
  controllers/subreconciler.go
  controllers/trustyaiservice_controller.go
Labels: kind/enhancement, ok-to-test
