Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-11, with the labels that each got.

#351 RHOAIENG-15105: Add offline support for LMEvalJobs
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/constants.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval

#340 feat: support more customization for the job pod of the LMES
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: ok-to-test, lm-eval

#356 fix(test): Allow smoke test to pass
  .github/workflows/smoke.yaml
  tests/smoke/test_smoke.sh
Labels: ok-to-test, lgtm

#313 Add initial Kueue integration
  Dockerfile.lmes-job
  api/lmes/v1alpha1/lmevaljob_types.go
  cmd/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  config/rbac/role.yaml
  controllers/controllers.go
  controllers/job_mgr.go
  controllers/job_mgr/README.md
  controllers/job_mgr/constants.go
  controllers/job_mgr/job_mgr_controller.go
  controllers/lmes/config.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  controllers/lmes/storage.go
  controllers/tas/statuses_test.go
  controllers/tas/storage.go
  controllers/tas/suite_test.go
  controllers/tas/trustyaiservice_controller.go
  go.mod
  go.sum
Labels: ok-to-test, lm-eval

#357 fix(RHOAIENG-9600): Ensure proper finalizer order and KServe logger r…
  controllers/tas/finalizers.go
  controllers/tas/trustyaiservice_controller.go
Labels: kind/bug, ok-to-test, lgtm

#358 fix(lmeval): Send Job logs to Pod StdOut
  controllers/lmes/driver/driver.go
Labels: ok-to-test, lgtm

#355 fix(RHOAIENG-14321): Revert metrics service target port to https
  config/rbac/auth_proxy_service.yaml
Labels: kind/bug, ok-to-test, lgtm

#360 chore(dependencies): Add Watsonx LLM support to LMEval Job image
  Dockerfile.lmes-job
Labels: kind/enhancement, lgtm, dependencies, lm-eval

#364 feat(lmeval): Add overlay for Kueue support
  config/overlays/odh-kueue/kustomization.yaml
  config/overlays/odh-kueue/params.env
  config/overlays/odh-kueue/patch.yaml
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval

#365 chore(release): Release 1.29.0
  Makefile
  config/base/params.env
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#361 feat(tas): Re-enable KServe Raw support
  controllers/tas/deployment_test.go
  controllers/tas/inference_services.go
  controllers/tas/statuses_test.go
  controllers/utils/utils.go
  go.sum
Labels: kind/enhancement, ok-to-test, lgtm

#370 feat(lmeval): Add offline mode as default
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement

#371 feat(lmeval): Disable remote code execution
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement
