Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-09, with the labels that each got.

#287 RHOAIENG-12274: Update operator's overlays
  config/overlays/odh/params.env
  config/overlays/rhoai/kustomization.yaml
  config/overlays/rhoai/params.env
Labels: kind/enhancement, lgtm

#289 Add devflag printout to GH Action comment
  .github/workflows/build-and-push.yaml
Labels: ok-to-test, lgtm

#290 feat: support batch size
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/base/params.env
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  config/overlays/lmes/kustomization.yaml
  config/overlays/lmes/lmes-only-patch.yaml
  config/overlays/rhoai/kustomization.yaml
  config/overlays/rhoai/tas-only-patch.yaml
  controllers/lmes/constants.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: lgtm, lm-eval

#292 fix: add the `openai` package into the lmes job image
  Dockerfile.lmes-job
Labels: lgtm, lm-eval

#293 Bump release 1.26.0/0.20.0
  Makefile
  config/overlays/odh/params.env
  controllers/version.go
Labels: lgtm, release

#298 feat: add device detection in lmes driver
  cmd/lmes_driver/main.go
  controllers/lmes/constants.go
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: feature, ok-to-test, lgtm, lm-eval

#301 feat: support unitxt recipes
  Dockerfile.lmes-job
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  cmd/lmes_driver/main_test.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/constants.go
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: feature, ok-to-test, lgtm, lm-eval

#305 CI: Add timeout loop to DSC install
  tests/scripts/install.sh
Labels: ok-to-test, lgtm

#304 RHOAIENG-13625: Add DBAvailable status to CR
  README.md
  config/base/params.env
  config/overlays/odh/params.env
  controllers/constants.go
  controllers/database.go
  controllers/deployment.go
  controllers/statuses.go
  controllers/statuses_test.go
  controllers/suite_test.go
  controllers/trustyaiservice_controller.go
Labels: kind/enhancement
