Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-03, with the labels that each got.

#222 Add GH Actions smoke tests to the operator
  .github/workflows/smoke.yaml
  tests/smoke/manifests/trustyai-cr.yaml
  tests/smoke/test_smoke.sh
Labels: kind/enhancement, lgtm

#225 Update params.env
  config/base/params.env
Labels: lgtm, release

#228 CI: Add checks to ensure ODH operator has spun up before proceeding
  .gitignore
  tests/scripts/install.sh
Labels: ok-to-test, lgtm

#226 RHOAIENG-4870: Update sdk-go version
  Makefile
  go.mod
Labels: ok-to-test, dependencies

#229 RHOAIENG-4870: Replace go-sdk version
  go.mod
  go.sum
Labels: ok-to-test, lgtm, dependencies
