Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-06, with the labels that each got.

#244 Release 0.15.0/1.21.0
  Makefile
  config/base/params.env
  controllers/version.go
Labels: ok-to-test, lgtm, release

#245 Move test image to ubi
  tests/Dockerfile
Labels: lgtm

#250 Add internal service TLS
  config/crd/bases/trustyai.opendatahub.io_trustyaiservices.yaml
  config/rbac/role.yaml
  controllers/constants.go
  controllers/templates/service/deployment.tmpl.yaml
  controllers/templates/service/service-internal.tmpl.yaml
Labels: kind/enhancement, ok-to-test, lgtm

#251 feat: Add testing overlay
  config/overlays/testing/image-pull-policy.yaml
  config/overlays/testing/kustomization.yaml
Labels: kind/enhancement, ok-to-test, lgtm

#252 Release v0.16.0/v1.22.0
  Makefile
  config/base/params.env
  config/overlays/odh/params.env
  controllers/version.go
Labels: lgtm, release

#253 RHOAIENG-8648: Update Go builder and toolset to 1.21
  Dockerfile
  go.mod
  go.sum
Labels: kind/bug, ok-to-test, lgtm, dependencies
