Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-10, with the labels that each got.

#310 Bump release 1.27.0/0.21.0
  Makefile
  config/overlays/odh/params.env
  controllers/version.go
Labels: lgtm, release

#309 feat: support custom dataset
  Dockerfile.lmes-job
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  cmd/lmes_driver/main_test.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: feature, lgtm, lm-eval

#315 Add KServe destination rule for Inference Services in the ServiceMesh
  config/overlays/odh/params.env
  config/rbac/role.yaml
  controllers/destination_rule.go
  controllers/inference_services.go
  controllers/templates/service/destination-rule.tmpl.yaml
  controllers/trustyaiservice_controller.go
Labels: kind/bug, ok-to-test, lgtm

#314 feat: new pulling mechanism for job statuses
  cmd/lmes_driver/main.go
  cmd/lmes_driver/main_test.go
  config/base/params.env
  config/manager/kustomization.yaml
  config/manager/service.yaml
  config/overlays/lmes/kustomization.yaml
  config/overlays/odh/kustomization.yaml
  config/rbac/role.yaml
  controllers/lmes/api/v1beta1/update_status.pb.go
  controllers/lmes/api/v1beta1/update_status.proto
  controllers/lmes/api/v1beta1/update_status_grpc.pb.go
  controllers/lmes/constants.go
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/grpc_server.go
  controllers/lmes/grpc_server_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  go.mod
  go.sum
Labels: ok-to-test, lgtm, lm-eval

#320 RHOAIENG-14321: Fix operator metrics service target port
  config/rbac/auth_proxy_service.yaml
Labels: kind/bug, lgtm

#295 Move operator's cmd/operator/main.go
  Dockerfile
  Makefile
  cmd/main.go
Labels: kind/enhancement, ok-to-test, lgtm

#322 RHOAIENG-13846: Remove hardcoded job's user ID
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm

#321 RHOAIENG-11109: Enable KServe serverless in the rhoai overlay
  config/base/params.env
  config/overlays/rhoai/params.env
Labels: kind/enhancement, lgtm

#331 CI: Update all overlay images after build+push
  .github/workflows/build-and-push.yaml
Labels: ok-to-test, lgtm

#324 Add correct CA cert to JDBC
  controllers/deployment.go
  controllers/templates/service/deployment.tmpl.yaml
Labels: kind/bug, ok-to-test

#332 Support for VirtualServices for InferenceLogger traffic
  config/rbac/role.yaml
  controllers/inference_services.go
  controllers/templates/service/virtual-service.tmpl.yaml
  controllers/trustyaiservice_controller.go
  controllers/utils.go
  controllers/virtual_service.go
Labels: kind/bug, lgtm

#330 LM-Eval: Fix flaky mkdir command in lmes-job Dockerfile
  Dockerfile.lmes-job
Labels: lgtm, lm-eval

#323 Refactor some lmesreconcile methods
  controllers/lmes/config.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: ok-to-test, lgtm, needs-ok-to-test, lm-eval

#333 tidy: clean up lmes-job image
  Dockerfile.lmes-job
Labels: lgtm, lm-eval

#336 sync: sync up dev/lm-eval branch with main branch
  .github/workflows/build-and-push.yaml
  README.md
  cmd/main.go
  config/base/params.env
  config/overlays/rhoai/kustomization.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  controllers/tas/constants.go
  controllers/tas/database.go
  controllers/tas/deployment.go
  controllers/tas/destination_rule.go
  controllers/tas/inference_services.go
  controllers/tas/statuses.go
  controllers/tas/statuses_test.go
  controllers/tas/suite_test.go
  controllers/tas/templates/service/deployment.tmpl.yaml
  controllers/tas/templates/service/destination-rule.tmpl.yaml
  controllers/tas/templates/service/virtual-service.tmpl.yaml
  controllers/tas/trustyaiservice_controller.go
  controllers/tas/virtual_service.go
  controllers/utils/utils.go
  go.mod
  go.sum
  tests/Dockerfile
  tests/Makefile
  tests/README.md
  tests/scripts/install.sh
Labels: ok-to-test, lgtm, lm-eval

#338 Update GH Action build and push comment, add LMH images to manifests
  .github/workflows/build-and-push.yaml
Labels: lgtm

#329 CI: Sync logging + makefile with service
  tests/Makefile
  tests/scripts/install.sh
Labels: ok-to-test, lgtm

#341 Checkout current LMEH release from midstream
  Dockerfile.lmes-job
Labels: ok-to-test, lgtm, dependencies, lm-eval

#342 Add Go report card to README.md
  README.md
Labels: documentation, lgtm

#343 Release 1.28.0
  Makefile
  config/base/params.env
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#347 Add PVC management
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/constants.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  controllers/lmes/storage.go
  go.sum
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval

#350 RHOAIENG-14773: Change batchSize to string in order to support "auto" and "auto:N"
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/config.go
  controllers/lmes/constants.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval
