Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-12, with the labels that each got.

#374 feat(RHOAIENG-15495): Add component metadata manifest
  config/component_metadata.yaml
Labels: kind/enhancement, ok-to-test, lgtm

#369 fix(lmeval): Disallow empty nodeAffinity
  controllers/job_mgr/README.md
  controllers/job_mgr/job_mgr_controller.go
Labels: kind/bug, ok-to-test, lgtm, needs-ok-to-test

#375 feat(lmeval): Disable online evaluation
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm

#377 feat(lmeval): Add offline metrics to LMEval job image
  Dockerfile.lmes-job
Labels: kind/enhancement, ok-to-test, lgtm, dependencies

#378 chore(release): v1.30.0/v0.24.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, release

#379 feat(lmeval): Add operator online and execution feature flag
  config/base/params.env
  config/overlays/odh-kueue/params.env
  config/overlays/odh/params.env
  config/overlays/rhoai/params.env
  controllers/lmes/config.go
  controllers/lmes/constants.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test

#381 feat(lmeval): Filter protected env vars set from CR directly
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test

#384 fix(CVE-2024-45338): Update golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, dependencies
