Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-07, with the labels that each got.

#254 Update for release 1.23
  Makefile
  config/base/params.env
  controllers/version.go
Labels: lgtm, release

#246 feat: Initial database support
  api/v1alpha1/trustyaiservice_types.go
  config/crd/bases/trustyai.opendatahub.io_trustyaiservices.yaml
  controllers/constants.go
  controllers/deployment.go
  controllers/deployment_test.go
  controllers/monitor_test.go
  controllers/route.go
  controllers/route_test.go
  controllers/secrets.go
  controllers/service_accounts_test.go
  controllers/statuses.go
  controllers/statuses_test.go
  controllers/storage_test.go
  controllers/suite_test.go
  controllers/templates/service/deployment.tmpl.yaml
  controllers/trustyaiservice_controller.go
Labels: kind/enhancement, ok-to-test, lgtm

#255 feat: Add TLS certificate mount on ModelMesh
  controllers/certificates.go
  controllers/constants.go
  controllers/inference_services.go
  controllers/utils.go
Labels: kind/enhancement

#261 fix: Fix typo in operator's arguments
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  config/manager/manager.yaml
Labels: kind/bug, ok-to-test, lgtm

#263 CI: Pin oc version, ubi version
  tests/Dockerfile
Labels: lgtm

#262 fix: Skip InferenceService patching for KServe RawDeployment [RHOAIENG-10500]
  controllers/inference_services.go
Labels: kind/enhancement, ok-to-test, lgtm

#267 feat: ConfigMap key to disable KServe Serverless configuration
  config/base/kustomization.yaml
  config/base/params.env
  controllers/config_maps.go
  controllers/constants.go
  controllers/inference_services.go
Labels: kind/enhancement, ok-to-test, lgtm
