Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2024-08, with the labels that each got.

#259 feat: Add support for custom certificates in database connection
  controllers/deployment.go
  controllers/secrets.go
  controllers/templates/service/deployment.tmpl.yaml
Labels: kind/enhancement, ok-to-test

#268 Add TLS endpoint for ModelMesh payload processors.
  controllers/inference_services.go
  controllers/utils.go
Labels: kind/enhancement, lgtm

#270 Update for release 1.24
  Makefile
  config/base/params.env
  config/overlays/odh/params.env
  controllers/version.go
Labels: ok-to-test, lgtm, release

#275 fix: Correct maxSurge and maxUnavailable
  controllers/templates/service/deployment.tmpl.yaml
Labels: kind/bug, ok-to-test, lgtm

#272 feat: Add LMES driver build to GHA
  .github/workflows/build-and-push.yaml
Labels: kind/enhancement, ok-to-test, lgtm

#257 feat: Add support for custom DB names
  controllers/deployment_test.go
  controllers/secrets.go
  controllers/suite_test.go
  controllers/templates/service/deployment.tmpl.yaml
Labels: kind/enhancement, lgtm

#279 [CI] Run tests from trustyai-tests
  tests/Dockerfile
  tests/Makefile
  tests/README.md
Labels: ok-to-test, lgtm

#278 Weekly sync up of dev/lm-eval branch
  controllers/tas/config_maps.go
  controllers/tas/constants.go
  controllers/tas/deployment.go
  controllers/tas/deployment_test.go
  controllers/tas/inference_services.go
  controllers/tas/secrets.go
  controllers/tas/suite_test.go
  controllers/tas/templates/service/deployment.tmpl.yaml
  controllers/utils/utils.go
Labels: lgtm, lm-eval

#280 feat: Driver updates job's status periodically
  Dockerfile.driver
  cmd/lmes_driver/main.go
  controllers/lmes/constants.go
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
Labels: lm-eval

#276 feat: Add Dockerfile for LMES job image
  Dockerfile.lmes-job
  patch/lmes/models.patch
Labels: lgtm, lm-eval

#282 Bump release 1.25.0/0.19.0
  Makefile
  config/base/params.env
  controllers/version.go
Labels: lgtm, release

#284 RHOAIENG-11969: Add job image build
  .github/workflows/build-and-push.yaml
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval

#285 RHOAIENG-11968: Change job image use midstream lm-evaluation-harness
  Dockerfile.lmes-job
Labels: kind/enhancement, ok-to-test, lgtm, dependencies
