Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-07, with the labels that each got.

#515 chore: Bump ODH LMEval job to 0.4.9rc0
  config/overlays/odh/params.env
Labels: ok-to-test, lgtm, dependencies

#521 fix: Bump LMEval driver to 1.40.0
  config/overlays/odh/params.env
Labels: kind/bug, lgtm

#517 fix: Allow task names with parentheses in LMEval Job CR
  controllers/lmes/patterns.go
  controllers/lmes/validation.go
Labels: kind/enhancement, lgtm

#513 Feat: Add Prometheus metric collection to operator, add LM-Eval usage metrics
  config/base/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/metrics-service.yaml
  config/prometheus/operator-service-monitor.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/metrics/metrics.go
Labels: ok-to-test

#529 feat: Add OCI artifact output support to LMEvalJob
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  controllers/lmes/lmevaljob_controller_validation_test.go
  controllers/lmes/validation.go
Labels: kind/enhancement

#514 Feat: Add Guardrails usage metrics (depends on #513)
  controllers/gorch/guardrailsorchestrator_controller.go
  controllers/metrics/metrics.go
Labels: ok-to-test, lgtm

#530 feat: Add subject to LMEval CRD's OCI outputs
  api/lmes/v1alpha1/lmevaljob_types.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, lgtm, lm-eval
