Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-02, with the labels that each got.

#398 chore(lmeval): Move LMEval to release 0.4.6
  Dockerfile.lmes-job
Labels: ok-to-test, lgtm, dependencies

#397 fix: Run PodExec against the main container
  controllers/lmes/lmevaljob_controller.go
Labels: ok-to-test, lgtm

#390 fix(CVE-2024-45337): Enforce x/crypto 0.31.0
  go.mod
  go.sum
Labels: lgtm, dependencies

#402 chore(release): Release v1.32.0/v0.25.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#400 fix(tas): Remove generic deployment watcher
  .github/workflows/smoke.yaml
  config/rbac/role.yaml
  controllers/tas/trustyaiservice_controller.go
  tests/crds/serving.kserve.io_servingruntimes.yaml
Labels: kind/enhancement, ok-to-test, lgtm

#409 feat(LMES): Switch LMES driver to a container port
  cmd/lmes_driver/main.go
  controllers/lmes/config.go
  controllers/lmes/constants.go
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm, lm-eval

#399 feat(lmeval): Add support for S3 offline assets
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  go.sum
Labels: kind/enhancement, ok-to-test, lgtm

#410 fix(guardrails): Add correct orchestrator container manifest name
  .github/workflows/build-and-push.yaml
Labels: kind/bug

#411 fix(guardrails): Fix orchestrator container manifest
  Dockerfile.orchestrator
Labels: kind/bug, lgtm

#413 chore(RHOAIENG-19906): Add guardrails to components
  config/component_metadata.yaml
Labels: lgtm

#406 CI: Migrate to Python tests, further unify testing between service+operator
  tests/Dockerfile
  tests/Makefile
  tests/README.md
  tests/TESTING.md
  tests/scripts/install.sh
Labels: ok-to-test

#414 fix(CVE-2024-28110): Fix cloudevents-sdk target version
  go.mod
  go.sum
Labels: kind/bug, ok-to-test, lgtm, dependencies

#417 fix(guardrails): Get orchestrator image from operator's ConfigMap
  controllers/gorch/constants.go
  controllers/gorch/deployment.go
  controllers/gorch/guardrailsorchestrator_controller_test.go
Labels: kind/bug, lgtm

#419 Fix: Typo in guardrailsorchestrator_controller.go
  controllers/gorch/guardrailsorchestrator_controller.go
Labels: ok-to-test, lgtm

#420 fix(RHOAIENG-20116): Use correct ConfigMap for orchestrator image config
  controllers/gorch/configmap.go
  controllers/gorch/deployment.go
Labels: kind/bug, ok-to-test, lgtm

#404 feat(LMES): Support custom template and prompt
  Dockerfile.lmes-job
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: kind/enhancement, ok-to-test, lgtm

#421 chore: Clean up module dependencies
  go.sum
Labels: ok-to-test, lgtm, dependencies

#423 docs: Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, lgtm

#422 chore(release): Release v1.33.0/v0.26.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#425 fix(RHOAIENG-6720): Remove Kustomize v5 deprecation warnings
  .github/workflows/smoke.yaml
  config/base/kustomization.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/overlays/lmes/kustomization.yaml
  config/overlays/odh-kueue/kustomization.yaml
  config/overlays/testing/kustomization.yaml
  tests/smoke/test_smoke.sh
Labels: kind/enhancement, ok-to-test, lgtm

#346 feat: Add Trivy scans to images
  .github/workflows/build-and-push.yaml
Labels: kind/enhancement, ok-to-test, lgtm
