Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-06, with the labels that each got.

#491 fix: Replace guardrails sidecar gateway image
  config/base/params.env
  config/overlays/odh/params.env
Labels: ok-to-test, lgtm

#497 fix: Move Trivy scan to separate action
  .github/workflows/build-and-push.yaml
  .github/workflows/security-scan.yaml
Labels: kind/bug, ok-to-test, lgtm

#502 CI: Fix broken image substitution
  .github/workflows/build-and-push.yaml
Labels: ok-to-test

#509 feat(RHOAIENG-28020): Add gosec code scanning
  .github/workflows/gosec.yaml
  README.md
Labels: kind/enhancement
