Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-04, with the labels that each got.

#437 chore: Release v1.35.0/v0.28.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#435 feat(RHOAIENG-22430): Add custom YAML task support to LMEval
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
  go.mod
  go.sum
Labels: kind/enhancement, ok-to-test, lgtm

#441 Add write permissions on PRs for GH Actions
  .github/workflows/build-and-push.yaml
Labels: ok-to-test, lgtm

#440 fix(RHOAIENG-23665): Allow non-admins to deploy and list LMEval jobs
  config/rbac/auth-delegator.yml
  config/rbac/default_lmeval_user_rolebinding.yaml
  config/rbac/kustomization.yaml
  config/rbac/non_admin_lmeval_role.yaml
Labels: kind/bug, ok-to-test

#438 RHOAIENG-23547: Decouple vllm-gateway and regex detector
  api/gorch/v1alpha1/guardrailsorchestrator_types.go
  api/gorch/v1alpha1/zz_generated.deepcopy.go
  config/base/params.env
  config/crd/bases/trustyai.opendatahub.io_guardrailsorchestrators.yaml
  config/overlays/odh/params.env
  config/overlays/rhoai/params.env
  controllers/gorch/constants.go
  controllers/gorch/deployment.go
  controllers/gorch/guardrailsorchestrator_controller_test.go
  controllers/gorch/templates/deployment.tmpl.yaml
  controllers/gorch/templates/service.tmpl.yaml
Labels: ok-to-test, lgtm

#443 chore: Replace golang.org/x/oauth2 0.18.0 with 0.27.0
  Dockerfile
  Dockerfile.driver
  go.mod
  go.sum
Labels: kind/bug, kind/enhancement, ok-to-test, lgtm

#444 chore: Update component metadata
  config/component_metadata.yaml
Labels: kind/enhancement, ok-to-test

#447 fix(RHOAIENG-23562): Update OAuth proxy image in RHOAI overlay
  config/overlays/rhoai/params.env
Labels: kind/bug, kind/enhancement, ok-to-test, lgtm

#436 feat: Support custom metrics and tasks
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  cmd/lmes_driver/main.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/driver/driver.go
  controllers/lmes/driver/driver_test.go
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_suite_test.go
  controllers/lmes/lmevaljob_controller_test.go
  controllers/tas/suite_test.go
Labels: ok-to-test, lgtm

#453 chore: Update lm-evaluation-harness release branch to 0.4.8
  Dockerfile.lmes-job
Labels: ok-to-test, lgtm, dependencies

#454 chore: Release/1.36.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release
