Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-03, with the labels that each got.

#429 chore(RHOAIENG-15495): Update main component metadata with correct branches
  config/component_metadata.yaml
Labels: kind/enhancement, lgtm

#426 feat( RHOAIENG-20330): Update GuardrailsOrchestrator unit tests
  controllers/gorch/guardrailsorchestrator_controller_test.go
  controllers/gorch/suite_test.go
Labels: lgtm, needs-ok-to-test

#430 fix: Use final Kustomize deployment name for operator image
  config/base/kustomization.yaml
Labels: kind/bug, lgtm

#431 chore(release): Release v1.34.0/v0.27.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  controllers/constants/version.go
Labels: ok-to-test, lgtm, release

#432 Revert "fix(RHOAIENG-6720): Remove Kustomize v5 deprecation warnings (#425)"
  config/base/kustomization.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/overlays/lmes/kustomization.yaml
  config/overlays/odh-kueue/kustomization.yaml
  config/overlays/testing/kustomization.yaml
Labels: kind/bug, lgtm
