Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-05, with the labels that each got.

#456 chore: Create dependabot.yml
  .github/dependabot.yml
Labels: kind/enhancement, ok-to-test, lgtm

#466 fix: Correct sidecar gateway image name
  config/overlays/rhoai/params.env
Labels: ok-to-test, lgtm, dependencies

#469 chore: enable cgo in driver
  Dockerfile.driver
Labels: ok-to-test, lgtm, go

#472 fix: Correct gateway port to 8090
  controllers/gorch/guardrailsorchestrator_controller_test.go
  controllers/gorch/templates/service.tmpl.yaml
Labels: ok-to-test, lgtm

#473 fix: rename external guardrails route
  controllers/gorch/guardrailsorchestrator_controller.go
  controllers/gorch/guardrailsorchestrator_controller_test.go
  controllers/gorch/route.go
  controllers/gorch/templates/https-route.tmpl.yaml
Labels: ok-to-test, lgtm

#479 fix: cgo permission denied on LMEval driver
  Dockerfile.driver
Labels: kind/bug, ok-to-test, lgtm

#478 fix: Bring orchestrator build in-line with upstream
  Dockerfile.orchestrator
Labels: ok-to-test, lgtm, dependencies

#480 chore: Release/1.37.0
  Makefile
  config/base/params.env
  config/component_metadata.yaml
  config/overlays/odh/params.env
  config/overlays/rhoai/params.env
  controllers/constants/version.go
Labels: ok-to-test, release

#483 chore: Upgrade orchestrator component to 0.9.4
  config/component_metadata.yaml
Labels: ok-to-test, lgtm

#482 RHOAIENG-26004: Add system instruction and chat template support to lmes
  api/lmes/v1alpha1/lmevaljob_types.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: ok-to-test

#485 fix: Refine chat template argument
  api/lmes/v1alpha1/lmevaljob_types.go
  api/lmes/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/trustyai.opendatahub.io_lmevaljobs.yaml
  controllers/lmes/lmevaljob_controller.go
  controllers/lmes/lmevaljob_controller_test.go
Labels: ok-to-test, lgtm
