Repository trustyai-explainability/trustyai-service-operator, pull requests merged in 2025-10, with the labels that each got.

#581 fix: Bypass auth for metrics
  controllers/gorch/guardrailsorchestrator_controller.go
  controllers/gorch/kube_rbac_proxy_config.go
  controllers/gorch/oauth.go
  controllers/gorch/templates/deployment.tmpl.yaml
  controllers/gorch/templates/kube-rbac-proxy/gateway-config.tmpl.yaml
  controllers/gorch/templates/kube-rbac-proxy/orchestrator-config.tmpl.yaml
  controllers/gorch/templates/parser.go
Labels: kind/enhancement

#583 fix: Enable upstream CI builds only on upstream
  .github/workflows/build-and-push.yaml
Labels: kind/enhancement, lgtm

#584 fix: Add correct RBAC proxy env parameter to match ODH operator
  config/base/kustomization.yaml
  config/base/params.env
  config/overlays/odh-kueue/params.env
  config/overlays/odh/params.env
  config/overlays/rhoai/params.env
  controllers/gorch/constants.go
  controllers/tas/constants.go
Labels: kind/enhancement

#558 Fix: Report reconciliation failures to CR status
  controllers/gorch/config_generation.go
  controllers/gorch/guardrailsorchestrator_controller.go
  controllers/gorch/status.go
Labels: ok-to-test
